const LifeboatTwo = [
    {
        id: 1,
        name: 'Elisabeth Allen',
        gender: 'Female',
        age: '29',
        class: '1st Class',
    },
    {
      id: 2,
      name: 'Charlotte Appleton',
      gender: 'Female',
      age: '53',
      class: '1st Class',
    },
    {
      id: 3,
      name: 'Joseph Boxhall',
      gender: 'Male',
      age: '28',
      class: 'Crew (Officer)',
    },
    {
      id: 4,
      name: 'Malvina Cornell',
      gender: 'Female',
      age: '55',
      class: '1st Class',
    },
    {
      id: 5,
      name: 'Minnie Coutts',
      gender: 'Female',
      age: '36',
      class: '3rd Class',
    },
    {
      id: 6,
      name: 'William Coutts',
      gender: 'Male',
      age: '9',
      class: '3rd Class',
    },
    {
      id: 7,
      name: 'Neville Coutts',
      gender: 'Male',
      age: '3',
      class: '3rd Class',
    },
    {
      id: 8,
      name: 'Mahala Douglas',
      gender: 'Male',
      age: '48',
      class: '1st Class',
    },
    {
      id: 9,
      name: 'John Ellis',
      gender: 'Male',
      age: '28',
      class: 'Crew (Victualling)',
    },
    {
      id: 10,
      name: 'James Johnstone',
      gender: 'Male',
      age: '52',
      class: 'Crew (Victualling)',
    },
    {
      id: 11,
      name: 'Anton Kink',
      gender: 'Male',
      age: '29',
      class: '3rd Class',
    },
    {
      id: 12,
      name: 'Luise Kink-Heilmann',
      gender: 'Female',
      age: '26',
      class: '3rd Class',
    },
    {
      id: 13,
      name: 'Luise Kink-Heilmann',
      gender: 'Female',
      age: '4',
      class: '3rd Class',
    },
    {
      id: 14,
      name: 'Emilie Kreuchen',
      gender: 'Female',
      age: '29',
      class: '1st Class',
    },
    {
      id: 15,
      name: 'Berthe Leroy',
      gender: 'Female',
      age: '27',
      class: '1st Class',
    },
    {
      id: 16,
      name: 'Georgette Madill',
      gender: 'Female',
      age: '16',
      class: '1st Class',
    },
    {
      id: 17,
      name: 'Frank Osman',
      gender: 'Male',
      age: '27',
      class: 'Crew (Deck)',
    },
    {
      id: 18,
      name: 'Elisabeth Robert',
      gender: 'Female',
      age: '43',
      class: '1st Class',
    }
]

export default LifeboatTwo